import { DepthConverter } from '../physics/depth-converter';
import { Gas } from '../gases/Gases';
import { Segment } from '../depths/Segments';
import { Tank } from './Tanks';
import { IConsumedMix } from './consumptionByMix';
import { ConsumptionOptions, GasVolumes, RmvContext, SegmentsConsumption } from './consumptionCommon';
import { BreathingModel } from '../ccr/BreathingModel';

/**
 * Gas consumed during the dive by one gas mixture in liters, regardless of tanks.
 */
export class ConsumedGas implements IConsumedMix {
    /**
     * @param gas The gas mixture
     * @param total Available gas, sum of all tanks start amount of this gas in liters
     * @param consumed Gas consumed during the dive in liters, not limited by total
     * @param reserve Gas needed for emergency ascent in liters, not limited by total
     */
    constructor(
        public readonly gas: Gas,
        public readonly total: number,
        public readonly consumed: number,
        public readonly reserve: number
    ) { }

    /** Consumed and reserve in liters */
    public get required(): number {
        return this.consumed + this.reserve;
    }

    /** Available gas covers both consumed and reserve */
    public get hasReserve(): boolean {
        return this.required <= this.total;
    }

    /** Liters representing the full chart, the higher from available or required */
    public get scale(): number {
        return Math.max(this.total, this.required);
    }

    /** Available gas in percents of scale */
    public get percentsAvailable(): number {
        return this.percentsOfScale(this.total);
    }

    /** Required gas in percents of scale */
    public get percentsRequired(): number {
        return this.percentsOfScale(this.required);
    }

    /** Consumed gas in percents of scale */
    public get percentsConsumed(): number {
        return this.percentsOfScale(this.consumed);
    }

    /** Reserve in percents of scale */
    public get percentsReserve(): number {
        return this.percentsOfScale(this.reserve);
    }

    private percentsOfScale(volume: number): number {
        const scale = this.scale;

        if (scale <= 0) {
            return 0;
        }

        return volume / scale * 100;
    }
}

/**
 * Calculates consumed gas and reserve grouped by gas mixture in liters, ignoring the tanks.
 */
export class ConsumptionByGas {
    /** Emergency ascent is always breathed as open circuit */
    private reserveConsumption: SegmentsConsumption;
    private planConsumption: SegmentsConsumption;

    /**
     * @param breathing Optional breathing model of the dive, open circuit if not provided.
     */
    constructor(depthConverter: DepthConverter, breathing?: BreathingModel) {
        this.reserveConsumption = new SegmentsConsumption(depthConverter);
        this.planConsumption = new SegmentsConsumption(depthConverter, breathing);
    }

    /**
     * Returns true, if all gases have enough gas available to cover consumed and reserve.
     * See also ConsumedGas.hasReserve
     */
    public static haveReserve(gases: ConsumedGas[]): boolean {
        return gases.every(g => g.hasReserve);
    }

    /**
     * Calculates the consumption per gas mixture, doesn't change the tanks.
     * @param segments Profile generated by algorithm including user defined + generated ascent,
     *                 the array needs have at least 3 items (descent, swim, ascent) and end at surface.
     * @param emergencyAscent Not null array of segments representing the special ascent.
     * @param tanks All tanks used to generate the profile, their gases need to fit all used in segments param
     * @param consumptionOptions Not null consumption definition.
     * @returns One item per distinct gas mixture in order of tanks.
     */
    public consume(segments: Segment[], emergencyAscent: Segment[], tanks: Tank[], consumptionOptions: ConsumptionOptions): ConsumedGas[] {
        SegmentsConsumption.validate(segments, emergencyAscent);
        const rmvContext = RmvContext.create(consumptionOptions, emergencyAscent, tanks);

        const reserves = this.reserveConsumption.toBeConsumedYet(emergencyAscent, new GasVolumes(),
            (s) => rmvContext.stressRmvPerSecond(s), () => true);
        const consumed = this.planConsumption.toBeConsumedYet(segments, new GasVolumes(),
            () => rmvContext.rmvPerSecond, () => true);

        return this.groupByGas(tanks).map(gasTanks => {
            const gas = gasTanks[0].gas;
            const gasCode = gas.contentCode;
            const total = gasTanks.reduce((sum, t) => sum + t.volume, 0);
            return new ConsumedGas(gas.copy(), total, consumed.get(gasCode), reserves.get(gasCode));
        });
    }

    private groupByGas(tanks: Tank[]): Tank[][] {
        const groups = new Map<number, Tank[]>();

        tanks.forEach(tank => {
            const gasCode = tank.gas.contentCode;
            const group = groups.get(gasCode) ?? [];
            group.push(tank);
            groups.set(gasCode, group);
        });

        return Array.from(groups.values());
    }
}
