import { Precision } from './precision';
import { AlgorithmParams, BuhlmannAlgorithm } from './BuhlmannAlgorithm';
import { DepthConverter } from './depth-converter';
import { Diver } from './Diver';
import { Gases } from './Gases';
import { Options } from './Options';
import { CalculatedProfile } from './CalculatedProfile';
import { Segment, Segments } from './Segments';
import { Tank, Tanks } from './Tanks';
import { Time } from './Time';
import { BinaryIntervalSearch, SearchContext } from './BinaryIntervalSearch';
import { PlanFactory } from './PlanFactory';

// TODO remove, if no longer relevant
class ConsumptionSegment {
    /** in seconds */
    public startTime = 0;
    /** in seconds */
    public endTime = 0;
    /** in meters */
    public averageDepth = 0;
    /** in meters */
    private _startDepth = 0;
    /** in meters */
    private _endDepth = 0;

    /**
     * @param duration in seconds
     * @param newDepth in meters
     * @param previousDepth in meters
     */
    private constructor(public duration: number, newDepth: number, previousDepth: number, averageDepth: number) {
        this.endTime = Precision.roundTwoDecimals(duration);
        this._endDepth = newDepth;
        this._startDepth = previousDepth;
        this.averageDepth = averageDepth;
    }

    /** in meters */
    public get startDepth(): number {
        return this._startDepth;
    }

    /** in meters */
    public get endDepth(): number {
        return this._endDepth;
    }

    public static fromSegment(segment: Segment): ConsumptionSegment {
        return new ConsumptionSegment(segment.duration, segment.endDepth, segment.startDepth, segment.averageDepth);
    }
}

export interface ConsumptionOptions {
    diver: Diver;
    /** Minimum tank reserve for first tank in bars */
    primaryTankReserve: number;
    /** Minimum tank reserve for all other stage tanks in bars */
    stageTankReserve: number;
}

/**
 * Calculates tank consumptions during the dive and related variables
 * (e.g. rock bottom, turn pressure, turn time)
 */
export class Consumption {
    /** Minimum bars to keep in first tank, even for shallow dives */
    public static readonly defaultPrimaryReserve = 30;
    /** Minimum bars to keep in stage tank, even for shallow dives */
    public static readonly defaultStageReserve = 20;

    constructor(private depthConverter: DepthConverter) { }

    private static calculateDecompression(segments: Segments, tanks: Tank[], options: Options): CalculatedProfile {
        const bGases = Gases.fromTanks(tanks);

        const algorithm = new BuhlmannAlgorithm();
        const segmentsCopy = segments.copy();
        const parameters = AlgorithmParams.forMultilevelDive(segmentsCopy, bGases, options);
        const profile = algorithm.decompression(parameters);
        return profile;
    }

    /**
     * Updates tanks consumption based on segments, also calculates emergency profile using the decompression algorithm.
     * So it is time consuming => Performance hit.
     * @param segments Profile generated by algorithm including user defined + generated ascent,
     *                 the array needs have at least 3 items (descent, swim, ascent).
     * @param options Not null profile behavior options.
     * @param tanks All tanks used to generate the profile, their gases need to fit all used in segments param
     * @param consumptionOptions Not null definition how to consume the gases.
     */
    public consumeFromTanks(segments: Segment[], options: Options, tanks: Tank[], consumptionOptions: ConsumptionOptions): void {
        if (segments.length < 2) {
            throw new Error('Profile needs to contain at least 2 segments.');
        }

        const emergencyAscent = PlanFactory.emergencyAscent(segments, options, tanks);
        this.consumeFromTanks2(segments, emergencyAscent, tanks, consumptionOptions);
    }

    /**
     * Updates tanks consumption based on segments, uses already calculated emergency ascent.
     * So it is time consuming => Performance hit.
     * @param segments Profile generated by algorithm including user defined + generated ascent,
     *                 the array needs have at least 3 items (descent, swim, ascent).
     * @param emergencyAscent Not null array of segments representing the special ascent.
     *                 Doesn't have to be part of the segments parameter value, since in emergency we need current state.
     * @param tanks All tanks used to generate the profile, their gases need to fit all used in segments param
     * @param consumptionOptions Not null consumption definition.
     */
    public consumeFromTanks2(segments: Segment[], emergencyAscent: Segment[], tanks: Tank[], consumptionOptions: ConsumptionOptions): void {
        if (segments.length < 2) {
            throw new Error('Profile needs to contain at least 2 segments.');
        }

        Tanks.resetConsumption(tanks);
        // Reserve needs to be first to be able preserve it.
        this.updateReserve(emergencyAscent, tanks, consumptionOptions);
        const tankMinimum = (t: Tank) => t.reserve;
        const rmv = consumptionOptions.diver.rmv;
        let remainToConsume: Map<number, number> = this.toBeConsumedYet(segments, rmv, new Map<number, number>(), (s) => !!s.tank);
        // First satisfy user defined segments where tank is assigned and only then try the rest.
        // assigned tank will be consumed from that tank directly
        // it is always user defined segment (also in ascent)
        remainToConsume = this.consumeByTanks(segments, remainToConsume, rmv, tankMinimum);
        remainToConsume = this.consumeByTanks2(segments, remainToConsume, () => 0);
        remainToConsume = this.toBeConsumedYet(segments, rmv, remainToConsume, (s) => !s.tank);
        remainToConsume = this.consumeByGases(tanks, remainToConsume, tankMinimum);
        this.consumeByGases(tanks, remainToConsume, () => 0);
    }

    /**
     * We cant provide this method for multilevel dives, because we don't know which segment to extend
     * @param sourceSegments User defined profile
     * @param tanks The tanks used during the dive to check available gases
     * @param consumptionOptions Not null consumption definition
     * @param options ppO2 definitions needed to estimate ascent profile
     * @returns Number of minutes representing maximum time we can spend as bottom time.
     * Returns 0 in case the duration is shorter than user defined segments.
     */
    public calculateMaxBottomTime(sourceSegments: Segments, tanks: Tank[],
        consumptionOptions: ConsumptionOptions, options: Options): number {
        const testSegments = this.createTestProfile(sourceSegments);
        const addedSegment = testSegments.last();

        const context: SearchContext = {
            // choosing the step based on typical dive duration
            estimationStep: Time.oneMinute * 40,
            initialValue: 0,
            maxValue: Time.oneDay,
            doWork: (newValue: number) => {
                addedSegment.duration = newValue;
                this.consumeFromProfile(testSegments, tanks, consumptionOptions, options);
            },
            meetsCondition: () => Tanks.haveReserve(tanks)
        };

        const interval = new BinaryIntervalSearch();
        const addedDuration = interval.search(context);

        // the estimated max. duration is shorter, than user defined segments
        if (addedDuration === 0) {
            return 0;
        }

        // Round down to minutes directly to ensure we are in range of enough value
        const totalDuration = Time.toMinutes(sourceSegments.duration + addedDuration);
        return Precision.floor(totalDuration);
    }

    private consumeFromProfile(testSegments: Segments, tanks: Tank[], consumptionOptions: ConsumptionOptions, options: Options) {
        const profile = Consumption.calculateDecompression(testSegments, tanks, options);
        this.consumeFromTanks(profile.segments, options, tanks, consumptionOptions);
    }

    private createTestProfile(sourceSegments: Segments): Segments {
        const testSegments = sourceSegments.copy();
        const lastUserSegment = sourceSegments.last();
        testSegments.addFlat(lastUserSegment.gas, 0);
        return testSegments;
    }

    private updateReserve(emergencyAscent: Segment[], tanks: Tank[], options: ConsumptionOptions): void {
        // here the consumed during emergency ascent means reserve
        // take all segments, because we expect all segments are not user defined => don't have tank assigned
        const gasesConsumed: Map<number, number> = this.toBeConsumedYet(emergencyAscent, options.diver.teamStressRmv,
            new Map<number, number>(), () => true);

        // add the reserve from opposite order than consumed gas
        for (let index = 0; index <= tanks.length - 1; index++) {
            const tank = tanks[index];
            const gasCode = tank.gas.contentCode();
            const consumedLiters = gasesConsumed.get(gasCode) || 0;
            this.updateTankReserve(tank, index, options, consumedLiters);
            let remaining = consumedLiters - (tank.reserve * tank.size);
            remaining = remaining > 0 ? remaining : 0;
            gasesConsumed.set(gasCode, remaining);
        }
    }

    private ensureMinimalReserve(reserve: number, tankIndex: number, options: ConsumptionOptions): number {
        // maybe use the tank.id instead of index
        const minimalReserve = tankIndex === 0 ? options.primaryTankReserve : options.stageTankReserve;

        if(reserve < minimalReserve) {
            return minimalReserve;
        }

        return reserve;
    }

    private updateTankReserve(tank: Tank, index: number, options: ConsumptionOptions, consumedLiters: number): void {
        const consumedBars = Precision.ceil(consumedLiters / tank.size);
        const tankConsumedBars = consumedBars > tank.startPressure ? tank.startPressure : consumedBars;
        tank.reserve = this.ensureMinimalReserve(tankConsumedBars, index, options);
    }

    private consumeByGases(tanks: Tank[], remainToConsume: Map<number, number>,
        minimum: (t: Tank) => number): Map<number, number> {
        // distribute the consumed liters across all tanks with that gas starting from last one
        // to consumed stages first. This simulates open circuit procedure: First consume, what you can drop.
        for (let index = tanks.length - 1; index >= 0; index--) {
            const tank = tanks[index];
            const gasCode = tank.gas.contentCode();
            let remaining = remainToConsume.get(gasCode) || 0;
            let reallyConsumed = this.consumeFromTank(tank, remaining, minimum);
            reallyConsumed = reallyConsumed < 0 ? 0 : reallyConsumed;
            remaining -= reallyConsumed;
            remaining = remaining < 0 ? 0 : remaining;
            remainToConsume.set(gasCode, remaining);
        }

        return remainToConsume;
    }

    private consumeByTanks2(segments: Segment[], remainToConsume: Map<number, number>,
        minimum: (t: Tank) => number): Map<number, number> {
        segments.forEach((segment: Segment) => {
            if (segment.tank) {
                const gasCode = segment.gas.contentCode();
                let remaining: number = remainToConsume.get(gasCode) || 0;
                let reallyConsumed = this.consumeFromTank(segment.tank, remaining, minimum);
                reallyConsumed = reallyConsumed < 0 ? 0 : reallyConsumed;
                remaining -= reallyConsumed;
                remaining = remaining < 0 ? 0 : remaining;
                remainToConsume.set(gasCode, remaining);
            }
        });

        return remainToConsume;
    }

    private consumeByTanks(segments: Segment[], remainToConsume: Map<number, number>,
        rmv: number, minimum: (t: Tank) => number): Map<number, number> {
        const rmvSeconds = Time.toMinutes(rmv);

        segments.forEach((segment: Segment) => {
            if (segment.tank) {
                const gasCode = segment.gas.contentCode();
                const consumptionSegment = ConsumptionSegment.fromSegment(segment);
                const consumedLiters = this.consumedBySegment(consumptionSegment, rmvSeconds);
                let reallyConsumed = this.consumeFromTank(segment.tank, consumedLiters, minimum);
                reallyConsumed = reallyConsumed < 0 ? 0 : reallyConsumed;
                let remaining: number = remainToConsume.get(gasCode) || 0;
                remaining -= reallyConsumed;
                remaining = remaining < 0 ? 0 : remaining;
                remainToConsume.set(gasCode, remaining);
            }
        });

        return remainToConsume;
    }

    /** Requires already calculated reserve */
    private consumeFromTank(tank: Tank, consumedLiters: number, minimum: (t: Tank) => number): number {
        const consumedBars = Precision.ceil(consumedLiters / tank.size);
        let available = tank.endPressure - minimum(tank);
        available = available > 0 ? available : 0;
        const tankConsumedBars = consumedBars > available ? available : consumedBars;
        tank.consumed += tankConsumedBars;
        return tankConsumedBars * tank.size; // TODO consider round by bars at end of the calculation
    }

    /** The only method which add gas to remainToConsume */
    private toBeConsumedYet(segments: Segment[], rmv: number,
        remainToConsume: Map<number, number>,
        includeSegment: (segment: Segment) => boolean): Map<number, number> {

        const rmvSeconds = Time.toMinutes(rmv);

        for (let index = 0; index < segments.length; index++) {
            const segment = segments[index];

            if (includeSegment(segment)) {
                const gas = segment.gas;
                const gasCode = gas.contentCode();
                const converted = ConsumptionSegment.fromSegment(segment);
                const consumedLiters = this.consumedBySegment(converted, rmvSeconds);
                let consumedByGas: number = remainToConsume.get(gasCode) || 0;
                consumedByGas += consumedLiters;
                remainToConsume.set(gasCode, consumedByGas);
            }
        }

        return remainToConsume;
    }

    /**
     * Returns consumption in Liters at given segment average depth
     * @param rmvSeconds Liter/second
     */
    private consumedBySegment(segment: ConsumptionSegment, rmvSeconds: number) {
        const averagePressure = this.depthConverter.toBar(segment.averageDepth);
        const consumed = segment.duration * averagePressure * rmvSeconds;
        return consumed;
    }
}

